// todo-react/src/views/Todo/index.js
import React, { useState, useEffect } from 'react';
import TodoCreate from '../../components/TodoCreate';
import TodoSearch from "../../components/TodoSearch";
import TodoItem from "../../components/TodoItem";
import TodoPagination from "../../components/TodoPagination";
import TodoApi from '../../api/todo';
import './style.scss';

function Todo() {
  const [todos, setTodos] = useState([]);
  useEffect(() => {
    const fetchData = async () => {
      const requestData = {
        condition: {},
        paging: {
          no: 1,
        },
      };
      const {data} = await TodoApi.list(requestData);
      const todos = data.todos.map((todo) => ({
        ...todo,
        referenceIds: todo.referenceIds.join(', '),
      }));
      setTodos(todos);
      // this.paging = data.paging;
    };
    fetchData();
  }, []);

  return (
    <div className="todo">
      <div className="todo__inner">
        <TodoCreate />
        <div className="todo__board">
          <TodoSearch />
          <ul className="todo__list">
            {todos.map(todo => (
              <li className="todo__list__item" key={todo.id}>
                <TodoItem todo={todo}/>
              </li>
            ))}
          </ul>
          <TodoPagination />
        </div>
      </div>
    </div>
  );
}

export default Todo;

// todo-vue/src/views/todo/index.vue
<template>
  <div class="todo">
    <h1 class="todo__title">TODO APP</h1>
    <div class="todo__inner">
      <todo-create @refresh-todo="refreshTodo"></todo-create>
      <div class="todo__board">
        <todo-search></todo-search>
        <ul>
          <li v-for="todo in todos" :key="todo.id">
            <todo-item :todo="todo"></todo-item>
          </li>
        </ul>
        <todo-pagination></todo-pagination>
      </div>
    </div>
  </div>
</template>

<script>
import TodoCreate from '@/components/TodoCreate/index.vue';
import TodoSearch from '@/components/TodoSearch/index.vue';
import TodoItem from '@/components/TodoItem/index.vue';
import TodoPagination from '@/components/TodoPagination/index.vue';
import TodoApi from '@/api/todo';

export default {
  components: {
    TodoCreate,
    TodoSearch,
    TodoItem,
    TodoPagination,
  },
  data() {
    return {
      todos: [],
    };
  },
  created() {
    this.initTodo();
  },
  methods: {
    initTodo() {
      TodoApi.list()
        .then((res) => {
          this.todos = res.data;
        })
        .catch((err) => console.log(err));
    },
    refreshTodo() {
      this.initTodo();
    },
  },
};
</script>

<style lang="scss" scoped src="./style.scss"></style>
