// todo-react/src/components/TodoItem/index.js
import React, { useState } from 'react';
import moment from "moment";
import './style.scss';

function TodoItem({ todo }) {
  const { id, content, createdAt, updatedAt, referenceIds, completed } = todo;
  const [isUpdate, setIsUpdate] = useState(false);
  const formatDate = (date) => moment(date).format('YYYY-MM-DD');
  const convertReferenceIds = (ids) => {
    let referenceIds = ids
      .split(',')
      .map((id) => parseInt(id.trim(), 10));
    referenceIds = referenceIds
      .filter((item, index) => referenceIds.indexOf(item) === index)
      .sort();
    return referenceIds;
  };
  const viewReferenceIds = (ids) => {
    return convertReferenceIds(ids).map((id) => `@${id}`).join(', ');
  };
  const handleUpdate = () => setIsUpdate(true);
  const handleCancel = () => {
    setIsUpdate(false);
  };
  const handleSubmit = () => {};
  const handleDelete = () => {};

  return (
    <div className="todo-item">
      <div className="todo-item__label checkbox">
        <input
          type="checkbox"
          className="todo-item__completed"
          minLength="1"
          maxLength="200" />
        <label
          className="todo-item__info"
          htmlFor="`todo-item-${todo.id}`">
          {isUpdate &&
            <input
              type="text"
              className="todo-content-update"
              value={content} />
          }
          {!isUpdate &&
            <strong className="todo-item__title">{content}</strong>
          }
          <span className="todo-item__id">ID: <em>{id}</em></span>
          <span className="todo-item__created">등록일: <em>{formatDate(createdAt)}</em></span>
          <span className="todo-item__updated">최종 수정일: <em>{formatDate(updatedAt)}</em></span>
          {isUpdate &&
            <input
              type="text"
              value={referenceIds}
              placeholder="참조 Todo id 입력 (예: 1, 2)"/>
          }
          {!isUpdate &&
            <span className="todo-item__ref">참조 Todo: <em>{viewReferenceIds(referenceIds)}</em></span>
          }
        </label>
      </div>
      <div className="todo-item__button">
        {!completed && !isUpdate &&
          <button
            type="button"
            className="button small"
            onClick={handleUpdate}>
            수정
          </button>
        }
        {isUpdate &&
          <>
            <button
              type="button"
              className="button small"
              onClick={handleSubmit(id)}>
              확인
            </button>
            <button
              type="button"
              className="button small"
              onClick={handleCancel}>
              취소
            </button>
          </>
        }
        <button
          type="button"
          className="button small"
          onClick={handleDelete(id)}>
          삭제
        </button>
      </div>
    </div>
  );
}

export default TodoItem;

// todo-vue/src/components/TodoItem/index.vue
<template>
  <div
    class="todo-item"
    :class="{'todo-item--completed': todo.completed}">
    <div class="todo-item__label checkbox">
      <input
        type="checkbox"
        class="todo-item__completed"
        v-model="completed"
        minlength="1"
        maxlength="200"
        :id="`todo-item-${todo.id}`"
        :disabled="isUpdate"
        @change="handleCompleted(todo.id)" />
      <label class="todo-item__info" :for="`todo-item-${todo.id}`">
        <input
          type="text"
          class="todo-content-update"
          v-if="isUpdate"
          v-model="content" />
        <strong v-else class="todo-item__title">{{ todo.content }}</strong>
        <span class="todo-item__id">ID: <em>{{ todo.id }}</em></span>
        <span class="todo-item__created">등록일: <em>{{ todo.createdAt | formatDate }}</em></span>
        <span class="todo-item__updated">최종 수정일: <em>{{ todo.updatedAt | formatDate }}</em></span>
        <input
          type="text"
          v-if="isUpdate"
          v-model="referenceId"
          placeholder="참조 Todo id 입력 (예: 1, 2)" />
        <span v-else class="todo-item__ref">참조 Todo: <em>{{ referenceIds }}</em></span>
      </label>
    </div>
    <div class="todo-item__button">
      <button
        type="button"
        class="button small"
        v-if="!todo.completed && !isUpdate"
        @click="handleUpdate">
        수정
      </button>
      <button
        type="button"
        class="button small"
        v-if="isUpdate"
        @click="handleSubmit(todo.id)">
        확인
      </button>
      <button
        type="button"
        class="button small"
        v-if="isUpdate"
        @click="handleCancel">
        취소
      </button>
      <button
        type="button"
        class="button small"
        @click="handleDelete(todo.id)">
        삭제
      </button>
    </div>
  </div>
</template>

<script>
import TodoApi from '@/api/todo';
import moment from 'moment';

export default {
  props: {
    todo: {
      type: Object,
      required: true,
    },
  },
  data() {
    return {
      completed: this.todo.completed,
      content: this.todo.content,
      referenceId: this.todo.referenceIds,
      isUpdate: false,
    };
  },
  filters: {
    formatDate: (date) => moment(date).format('YYYY-MM-DD'),
  },
  computed: {
    referenceIds() {
      const ids = this.convertReferenceIds(this.todo.referenceIds);
      return ids.map((id) => `@${id}`).join(', ');
    },
  },
  watch: {
    todo: {
      deep: true,
      handler(value) {
        this.completed = value.completed;
        this.content = value.content;
        this.referenceId = value.referenceIds;
      },
    },
  },
  methods: {
    convertReferenceIds(ids) {
      let referenceIds = ids
        .split(',')
        .map((id) => parseInt(id.trim(), 10));
      referenceIds = referenceIds
        .filter((item, index) => referenceIds.indexOf(item) === index)
        .sort();
      return referenceIds;
    },
    checkValidate() {
      const regex = /^[0-9, ]*$/g;
      if (!regex.test(this.referenceId)) {
        this.$toasted.show('참조 TODO 형식이 잘못되었습니다.');
        return false;
      }
      return true;
    },
    handleDelete(id) {
      TodoApi.delete(id)
        .then(() => {
          this.$emit('refresh-todo');
        })
        .catch((err) => console.log(err));
    },
    handleUpdate() {
      this.isUpdate = true;
    },
    async handleSubmit(id) {
      if (!this.checkValidate()) return false;
      const referenceIds = this.convertReferenceIds(this.referenceId);
      const requestData = {
        completed: this.completed,
        content: this.content,
        referenceIds,
      };
      try {
        await TodoApi.update(id, requestData);
        this.$emit('update-todo');
        this.isUpdate = false;
      } catch (err) {
        this.$toasted.show(err.response.data.errorMsg);
        return false;
      }
      return true;
    },
    handleCancel() {
      this.completed = this.todo.completed;
      this.content = this.todo.content;
      this.referenceId = this.todo.referenceIds;
      this.isUpdate = this.todo.completed;
    },
    async handleCompleted(id) {
      const success = await this.handleSubmit(id);
      if (!success) this.completed = !this.completed;
    },
  },
};
</script>

<style lang="scss" scoped src="./style.scss"></style>
