// todo-react/src/components/TodoPagination/index.js
import React from 'react';
import './style.scss';

function TodoPagination() {
  return (
    <div className="todo-pagination">
      <button
        type="button"
        className="todo-pagination__prev">
        <arrow-left />
      </button>
      <button
        type="button"
        className="todo-pagination__link">
        1
      </button>
      <button
        type="button"
        className="todo-pagination__next">
        <arrow-right />
      </button>
    </div>
  );
}

export default TodoPagination;

// todo-vue/src/components/TodoPagination/index.vue
<template>
  <div class="todo-pagination">
    <button
      type="button"
      class="todo-pagination__prev">
      Prev
    </button>
    <router-link
      to=""
      class="todo-pagination__link">
      1
    </router-link>
    <router-link
      to=""
      class="todo-pagination__link">
      2
    </router-link>
    <button
      type="button"
      class="todo-pagination__next">
      Next
    </button>
  </div>
</template>

<script>
export default {};
</script>

<style lang="scss" scoped src="./style.scss"></style>
