// todo-vue/src/components/TodoCreate/index.vue
<template>
  <div class="todo-create">
    <div class="todo-create__inner">
      <input
        type="text"
        v-model="content"
        placeholder="할 일을 입력해주세요."
        @keyup.enter="handleAddItem" />
      <button
        type="button"
        class="button"
        @click="handleAddItem">
        추가
      </button>
    </div>
  </div>
</template>

<script>
import TodoApi from '@/api/todo';

export default {
  data() {
    return {
      content: '',
    };
  },
  methods: {
    handleAddItem() {
      const request = {
        content: this.content,
      };
      TodoApi.create(request)
        .then(() => {
          this.$emit('refresh-todo');
          this.content = '';
        })
        .catch((err) => console.log(err));
    },
  },
};
</script>

<style lang="scss" scoped src="./style.scss"></style>

// todo-react/src/components/TodoCreate/index.js
import React, { useState } from 'react';
import TodoApi from '../../api/todo';
import './style.scss';

function TodoCreate() {
  const [content, setContent] = useState('');
  const onChange = (e) => {
    setContent(e.target.value);
  };
  const onClick = () => {
    const request = {
      content,
    };
    TodoApi.create(request)
      .then(() => {
        setContent('');
      })
      .catch(() => {});
  };
  const onKeyPress = (e) => {
    if (e.key === 'Enter') {
      onClick();
    }
  };

  return (
    <div className="todo-create">
      <div className="todo-create__inner">
        <input
          type="text"
          value={content}
          onChange={onChange}
          onKeyPress={onKeyPress}
          placeholder="할 일을 입력해주세요." />
        <button
          type="button"
          className="button"
          onClick={onClick}>
          추가
        </button>
      </div>
    </div>
  );
}

export default TodoCreate;
